# Generated by Django 4.2.5 on 2023-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAT_percentage', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('pay_on_arrival_discount_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('pay_online_discount_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('super_collision_damage_waiver_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('twu_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('baby_seat_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booster_seat_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roof_rack_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
