# Generated by Django 4.2.5 on 2023-09-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('CR', 'Car/Sedan'), ('VN', 'Van'), ('SV', 'SUV'), ('SP', 'Special'), ('Sw', 'Station Wagon')], default='CR', max_length=2)),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default='M', max_length=1)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['group'],
                'indexes': [models.Index(fields=['group'], name='car_categor_group_b1000f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='vehicles/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('bags', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='car.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='car_car_id_8edac1_idx'), models.Index(fields=['name'], name='car_car_name_4c7ddc_idx')],
            },
        ),
    ]
