# Generated by Django 4.2.5 on 2023-09-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='group',
            field=models.CharField(default='CR', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
