# Generated by Django 4.2.5 on 2023-09-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_group_remove_car_category_alter_car_transmission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicles',
        ),
        migrations.RenameIndex(
            model_name='vehicles',
            new_name='car_vehicle_id_ac0f54_idx',
            old_name='car_car_id_8edac1_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicles',
            new_name='car_vehicle_name_287c77_idx',
            old_name='car_car_name_4c7ddc_idx',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
