# Generated by Django 4.2.5 on 2023-09-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rename_car_vehicles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default='M', max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='vehicles/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('bags', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='car.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['id', 'slug'], name='car_vehicle_id_a61354_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['name'], name='car_vehicle_name_cf7d37_idx'),
        ),
    ]
