# Generated by Django 4.2.5 on 2023-09-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_vehicle_delete_vehicles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['category'],
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group'], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='car.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_category', to='car.category'),
        ),
    ]
