# Generated by Django 4.2.5 on 2023-09-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_sub_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='price',
            new_name='price_perday',
        ),
    ]
