# Generated by Django 4.2.5 on 2023-09-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_rename_price_vehicle_price_perday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bags',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='passengers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('A', 'Automatic'), ('M', 'Manual')], default='M', max_length=1),
        ),
    ]
