# Generated by Django 4.2.5 on 2023-09-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_vehicle_bags_alter_vehicle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup_datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pickup_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'pickup_location',
                'verbose_name_plural': 'pickup_locations',
                'ordering': ['pickup_location'],
            },
        ),
        migrations.CreateModel(
            name='Return_datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Return_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'return_location',
                'verbose_name_plural': 'return_locations',
                'ordering': ['return_location'],
            },
        ),
    ]
