# Generated by Django 4.2.5 on 2023-09-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_number_day_delete_pickup_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='period',
            field=models.CharField(blank=True, choices=[('WR', '(Winter rates'), ('SR', 'Summer rates'), ('SHR', 'Summer High rates')], max_length=3),
        ),
    ]
